### ISSUE TITLE
Can't connect to MySQL server on 'admin.local.dev' (111)

### ISSUE THREAD

**Issue by cristhianCMH** [pematon/adminer-custom#1]
Hello, I have a problem with adminer, I have a virtualhost responding to a local subdomain admin.local.dev, there have hosted repository and that's the mistake will not let me concetar that I can do, I have as user = root password = null

**Comment by peterpp** [comment]
Hello, this is not right place for questions about Adminer itself. Please, follow offical Adminer website here: http://www.adminer.org/. You can use its forum: http://sourceforge.net/p/adminer/discussion/

**Comment by cristhianCMH** [comment]
o.k thanks
