### ISSUE TITLE
Error: Non-static method Adminer::tableName() cannot be called statically in AdminerSimpleMenu.php:49

### ISSUE THREAD

**Issue by adrianbj** [pematon/adminer-custom#11]
Started getting this with PHP 8.

Maybe I am missing something, but seems like the simple fix is to change:
```
$name = Adminer::tableName($status);
```
to:
```
$name = $status['Name'];
```

**Comment by peterpp** [comment]
This is actually an issue of Adminer itself and I believe it is resolved in the current version (4.7.8).
