### ISSUE TITLE
Network Unreachable for Servers Behind Cloudflare.

### ISSUE THREAD

**Issue by chope1** [pematon/adminer-custom#14]
It's ideal not to select the default domain name as the server.
Leave it as a form field and let the users add their IP as the server, just like the default Adminer.

This will become an issue if the server is behind Cloudflare which will supply Cloudflare IP instead of the Origin IP.

**Comment by peterpp** [comment]
This repository contains a custom configuration for our own environment and needs. Consider it as an example, how Adminer can be configured. You can create our own bundle with modified index.php. Just remove the AdminerLoginServers plugin.
