### ISSUE TITLE
Theme looks different than the screenshot

### ISSUE THREAD

**Issue by dufferzafar** [pematon/adminer-custom#2]
I've just cloned the repo and setup adminer. And this is how it looks:

![adminer-odd-theme](https://cloud.githubusercontent.com/assets/1449512/9022057/9272c818-3882-11e5-864c-8e7b87a43d61.png)

As you can see a lot of the things look different from the screenshot on the main readme:
- All the `a` links are underlined. 
- The `Select`, `Search`, `Sort` & `Modify`, `Selected`, `Import`, `Export` take full length rather than a small width.
- The SQL statement is not syntax highlighted.
- The Sort and Search fields on each column look very odd.

For compariosn, here is the screenshot from the readme:

![Screenshot from readme](https://camo.githubusercontent.com/7fd1e3fad844b72f55ef22281a41d95d9ce85b0f/687474703a2f2f70656d61746f6e2e6769746875622e696f2f73637265656e73686f74732f61646d696e65722e706e673f33)

**Comment by peterpp** [comment]
Could you specify web browser and OS you use?

**Comment by dufferzafar** [comment]
Firefox 39.0 (also tested on Chrome 41) on Ubuntu 14.04.

**Comment by peterpp** [comment]
I assume that original Adminer CSS is not reachable. In HTML code is this linked style sheet:

```
<link rel="stylesheet" type="text/css" href="index.php?file=default.css&amp;version=4.2.2&amp;driver=mysql">
```

Please, be sure that this URL works well on your machine.

**Comment by peterpp** [comment]
I found similar behavior on one of my mobile devices. I had to clean browser cache and everything works fine now.
