### ISSUE TITLE
Can adminer-custom be used with sqlite?

### ISSUE THREAD

**Issue by peterdalydickson** [pematon/adminer-custom#5]
I was looking for a responsive theme for adminer, so thank you!

I used to have adminer working with sqlite, via...
```php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
  function adminer_object() 
  {
    class AdminerSoftware extends Adminer
      {
        function login($login, $password)
          {
            return ($login == 'admin' && $password == '******');
          }

        function loginForm() {
          echo '
            <table cellspacing="0">
            <tbody>
            <tr><th>Username</th>
            <td><input id="username" name="auth[username]" type="text" /></td>
            </tr/gt;
            <tr><th>Password</th>
            <td><input name="auth[password]" type="password" /></td>
            </tr/gt;
            </tbody/gt;
            </table>
          ';

          echo '<input type="submit" value="Login" />';
          echo '<input name="auth[driver]" type="hidden" value="sqlite" />';
          echo '<input name="auth[db]" type="hidden" value="macanta_install.db" />';
        }

        function database() {
          // database name, will be escaped by Adminer
          return 'macanta_install.db';
        }
      }
    return new AdminerSoftware;
  }
include "./adminer.php";
```

It's not obvious to me (I'm not a coder), how to get adminer-custom working with sqlite.

Can you point me in the right direction?

Thanks.

**Comment by peterpp** [comment]
Hello, this "adminer-custom" project is all-in-one bundle of Adminer for MySQL together with responsive theme and couple of other plugins. If you are interested just in the theme, the right place to look is here: https://github.com/pematon/adminer-theme

Note the "How to use" section in README.md.

Here is the code of index.php for your case:

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

function adminer_object()
{
  // Required to run any plugin.
  include_once "./plugins/plugin.php";

  // Plugins auto-loader.
  foreach (glob("plugins/*.php") as $filename) {
    include_once "./$filename";
  }

  // Specify enabled plugins here.
  $plugins = [
    // Put all required plugins here:
    // new AdminerSimpleMenu(),

    // AdminerTheme has to be the last one.
    new AdminerTheme(),
  ];

  class AdminerSoftware extends AdminerPlugin
  {
    function login($login, $password)
    {
      return ($login == 'admin' && $password == '******');
    }

    function loginForm()
    {
      echo '
        <table cellspacing="0">
        <tbody>
        <tr><th>Username</th>
        <td><input id="username" name="auth[username]" type="text" /></td>
        </tr/gt;
        <tr><th>Password</th>
        <td><input name="auth[password]" type="password" /></td>
        </tr/gt;
        </tbody/gt;
        </table>
      ';

      echo '<input type="submit" value="Login" />';
      echo '<input name="auth[driver]" type="hidden" value="sqlite" />';
      echo '<input name="auth[db]" type="hidden" value="macanta_install.db" />';
    }

    function database()
    {
      // database name, will be escaped by Adminer
      return 'macanta_install.db';
    }
  }

  return new AdminerSoftware($plugins);
}

include "./adminer.php";
```

**Comment by justinhartman** [comment]
@peterdalydickson if you'd like to use Adminer Custom for SQLite (or any other supported database type for that matter) I have a simple fix for you. While @peterpp is 100% right in his response I too wanted to use Adminer Custom out the box with both support for MySQL and Postgres and not just implement the theme as per Peter's suggestion. This is what I did to enable this.

Open up `index.php` and go to lines [16 to 18 of the index.php file](https://github.com/pematon/adminer-custom/blob/3eb58e2711cf185f8fd75fb4f1654ba4f0feb918/index.php#L16-L18). Comment out these lines to disable the `AdminerLoginServers` plugin.

### Old Code:

```php
new AdminerLoginServers([
    filter_input(INPUT_SERVER, 'HTTP_HOST') => filter_input(INPUT_SERVER, 'SERVER_NAME')
]),
```

### New Code:

```php
// new AdminerLoginServers([
//     filter_input(INPUT_SERVER, 'HTTP_HOST') => filter_input(INPUT_SERVER, 'SERVER_NAME')
// ]),
```
Once you have commented out the code, if you go back to your website, refresh the page and you should see a new `System` drop-down box above the `Server` box as per my screenshot below.

![New System Menu](https://dzwonsemrish7.cloudfront.net/items/3Q3H3x2C0g2q3E1X3Z35/Screen%20Shot%202018-04-27%20at%2020.56.26.png)

You can now use all the other supported engines. Enjoy!

**Comment by dgleba** [comment]
My solution is here..

Oops, I put in the wrong link. It is corrected now.

https://github.com/vrana/adminer/wiki/Enable-sqlite3

**Comment by peterpp** [comment]
@peterdalydickson, as others pointed out, you can use adminer-custom for sqlite database with few modifications. If you want to keep your modified index.php with custom login form, just use my example above and add all plugins:

``` php
    // Specify enabled plugins here.
    $plugins = [
        new AdminerSimpleMenu(),
        new AdminerCollations(),
        new AdminerJsonPreview(),

        // AdminerTheme has to be the last one.
        new AdminerTheme(),
    ];
```

However, I've just added support for SQLite directly to AdminerLoginServers 😲
Now, you can use index.php from adminer-custom and configure your database:

``` php
    new AdminerLoginServers([
        "sqlite://admin:password@macanta_install.db",
    ]),
```

As simple as that. Enjoy!
