### ISSUE TITLE
[Help Wanted] Adding servers to AdminerLoginServers plugin

### ISSUE THREAD

**Issue by duceduc** [pematon/adminer-custom#9]
Can some show me an example how I can add my own custom server to the AdminerLoginServers plugin file? My default isn't to 'localhost', but '192.168.1.20'

**Comment by peterpp** [comment]
Examples are directly in the source code of that plugin.

**Comment by duceduc** [comment]
Hi. I saw the plugin file and the samples , but I am still not understanding where to edit or insert my server info. So I edited this line in  index.php. It is not  the proper way of going about it , but seems to work.

	new AdminerLoginServers([
	'192.168.1.20' => 'ds1',
	filter_input(INPUT_SERVER, 'HTTP_HOST') => filter_input(INPUT_SERVER, 'SERVER_NAME'
	)

**Comment by peterpp** [comment]
index.php is the right place. This is the way how Adminer plugins are configured: https://www.adminer.org/en/plugins/#use

index.php in this repository is just our custom default setup.
